# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/ved_decoder/ved.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("lib/ved_decoder/ved.proto", :syntax => :proto2) do
    add_message "ved_decoder.Ved" do
      optional :index, :uint64, 1
      optional :type, :uint64, 2
      optional :sub_result_position, :uint64, 5
      optional :result_position, :uint64, 6
      optional :start_page, :uint64, 7
    end
  end
end

module VedDecoder
  Ved = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ved_decoder.Ved").msgclass
end
